
// import '2dlist.dart';
// import 'Inputs.dart';
// import 'OOP.dart';
// import 'OOP2.dart';
// import 'OOP3_ATM.dart';
// import 'OOP4.dart';
// import 'OOP5.dart';
// import 'OOP6_Inheritance.dart';
// import 'OOP7_eVoting.dart';
// import 'exception.dart';
// import 'functions.dart';
// import 'functions2.dart';
// import 'higherOrderFunction2.dart';
// import 'higherOrderFunctions.dart';
// import 'lambdaFunction.dart';
// import 'list.dart';
// import 'listHOF.dart';
// import 'loopsAndControlStatements.dart';
// import 'map.dart';
// import 'numberMethods.dart';
// import 'operators.dart';
// import 'outputs.dart';
// import 'recursion.dart';
// import 'sets.dart';
// import 'stringMethods.dart';
// import 'sumEvens.dart';
// import 'throwingException.dart';
// import 'typeCasting.dart';
// import 'variable.dart';
// import 'whereHOF.dart';

import 'OOP7_eVoting.dart';
import 'OOP8_Poly.dart';
import 'OOP9.dart';

void main(List<String> args) {
  // learningOutput();
  // learningVariables();
  // typeCasting();
  // learningInputs();
  // learningOperators();
  // learningLnCS();
  // numberMethods();
  // stringMethods();
  // learningException();
  // learningList();
  // learningList();
  // twoDList();
  // learningSets();
  // learningMap();
  // learningFunctions();
  // learningFunctions2();
  // recursion();
  // sumEvens();
  // throwingException();
  // lambdaFunction();
  // higherOrderFunctions();
  // higherOrderFunctions2();
  // whereHOF();
  // listHOF();
  // learningOOP();
  // learningOOP2();
  // oopATM();
  // learningOOP4();
  // learningOOP5();
  // learningOOP6();
  // mainEVoting();
  // learningOOP8();
  learningOOP9();
}